{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  {{- if .images }}
  annotations:
    argocd-image-updater.argoproj.io/image-list: {{ include "wiji-cluster.imageList" .images }}
    argocd-image-updater.argoproj.io/write-back-method: argocd
    {{- range .images }}
    argocd-image-updater.argoproj.io/{{ .alias }}.update-strategy: newest-build
    argocd-image-updater.argoproj.io/{{ .alias }}.helm.image-name: image.{{ .alias }}.name
    argocd-image-updater.argoproj.io/{{ .alias }}.helm.image-tag: image.{{ .alias }}.tag
    argocd-image-updater.argoproj.io/{{ .alias }}.pull-secret: pullsecret:{{ .pullSecret }}
    {{- end }}
  {{- end }}
spec:
  project: default
  source:
    repoURL: {{ .repoURL }}
    path: {{ .path }}
    targetRevision: {{ .branch }}
    helm:
      {{- if .valuesFile }}
      valueFiles:
        - {{ .valuesFile }}
      {{- end }}
      {{- if .images }}
      parameters:
        {{- range .images }}
        - name: image.{{ .alias }}.name
          value: {{ .image }}
        {{- end }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
